[package]
name = "exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
twmap = "0.12.0"

dirs = "5.0.1"
serde = "1.0.197"
serde_json = "1.0.115"
clap = { version = "4.5.4", features = ["derive", "cargo", "string"] }

mapgen_core = { package = "core", path = "../core" }
